[project]
name = "PyRite"
version = "0.1.0"
description = "A small collection of personal utility functions and plotting tools."
readme = "README.md"
authors = [
    { name="Krzysiek Lisiecki", email="Krzysztof.lisiecki@ncbj.gov.pl" }
]
requires-python = ">=3.10"
dependencies = [
    "matplotlib",
    "numpy",
    "astropy"
]

[project.urls]
Homepage = "https://github.com/lisieckik/PyRite"
Repository = "https://github.com/lisieckik/PyRite"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.package-data]
"PyRite.styles" = ["*.mplstyle"]